<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="HelixToolkit.Wpf" Version="2.20.2">
		  <NoWarn>NU1701</NoWarn>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation\Simulation.fsproj" />
  </ItemGroup>

</Project>
