<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Core.Wpf" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation\Simulation.fsproj" />
  </ItemGroup>

</Project>
