<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Vectors.fs" />
    <Compile Include="Simulation.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Maths" Version="2.15.0" />
  </ItemGroup>

</Project>
