<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
	 <TieredPGO>true</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Collections.ParallelSeq" Version="1.2.0" />
    <PackageReference Include="System.Windows.Extensions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simulation\Simulation.fsproj" />
  </ItemGroup>

</Project>
